version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.1

jobs:
   build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
    steps:
      - azure-acr/build-and-push-image:
          azure-password: Bani.d@1234 
          azure-tenant: '4972b988-4909-4f69-8875-24edabf79004' 
          azure-username: ramakrishna.diddele@thinkartha.com 
          dockerfile: Dockerfile 
          login-server-name: firstregistry28.azurecr.io 
          registry-name: firstregistry28 
          repo: simple-java-app 

workflows:
  example-workflow:
    jobs:
      - example-job
