version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.2.1
workflows:
    example-workflow:
      jobs:
        - azure-acr/build-and-push-image:
            login-server-name: firstregistry28.azure.io 
            repo: firstregistry28/simple-java-app 
            registry-name: firstregistry28 

